### DISCUSSION TITLE
Non-Root Changes

### DISCUSSION THREAD

**Discussion by ianweatherburn** [solid-pixel/uhf-server-docker#27] [Ideas]
Would you consider the following changes to allow the container to not run as root, but as a specified user (requires changes to the Dockerfile.uhf and docker-compose.yml), and to be able to customise the port in the healthcheck via the same .env value instead of having to hard-code any change.  
My reason for this changes is selfish, in that I wanted non-root privileges on the db.json file (for my remux container). I have implemented the below changes locally and the container is working as expected.

Also with the comskip enhancement, its runs asynchronously. Any suggestions on identifying when that process is complete, so I can safely grab the .ts file at that point (and not before). I see it generates a .cut and a .txt file.

The major changes below here are:
1. docker-compose.yml : user directive
2. docker-compose.yml : healthcheck [CMD-SHELL]
3. Dockerfile.uhf : groupadd & useradd for PGID/PUID
4. Dockerfile.uhf: chown -R uhf-server:uhf-server /var/lib/uhf-server

### Proposed docker-compose.yml
```
uhf-server:
    image: solidpixel/uhf-server:uhf-1.4.0-ffmpeg7.1.1-d1
    container_name: uhf-server
    restart: unless-stopped

    volumes:
      - ${DATA}/uhf-server/data:${SERVER}
      - ${MEDIA}/videos/uhf-server/recordings:${SERVER}/recordings

    ports:
      - ${API_PORT}:8000  

    user:
      ${PUID}:${PGID}

    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - RECORDINGS_DIR=${SERVER}/${RECORDINGS_DIR}
      - DB_PATH=${SERVER}/${DB_PATH}
      - LOG_LEVEL=${LOG_LEVEL}
      - PASSWORD=${PASSWORD}
      - ENABLE_COMMERCIAL_DETECTION=${ENABLE_COMMERCIAL_DETECTION}

    command:
      - sh
      - -c
      - |
          exec uhf-server \
            $${ENABLE_COMMERCIAL_DETECTION:+--enable-commercial-detection} \
            $${PASSWORD:+--password "$$PASSWORD"}

    healthcheck:
      [test: ["CMD-SHELL", "curl", "-f", "http://localhost:8000/server/stats"] # update URL if API_PORT changes](test: ["CMD-SHELL", "curl -f http://localhost:${API_PORT}/server/stats || exit 1"])
      interval: 30s
      timeout: 5s
      retries: 3
```

### .env file
```
# Environment
PGID=1000
PUID=1000

# Volumes
DATA=/home/iwadmin/docker/appdata
MEDIA=/home/media

# UHF-Server (Solid-Pixel Version)
SERVER=/var/lib/uhf-server
API_HOST=0.0.0.0
API_PORT=8003
RECORDINGS_DIR=/recordings
DB_PATH=/db.json
LOG_LEVEL=INFO
ENABLE_COMMERCIAL_DETECTION=true
PASSWORD=
TARGETARCH=amd64
UHF_VERSION=1.4.0
```

### Proposed Dockerfile.uhf
```
# Dockerfile
# Final image on Ubuntu 25.04
FROM ubuntu:25.04

# Define arguments for user and group IDs. These are now primarily for documentation
# or if you explicitly wanted to create a user with these IDs *if they were free*.
# For the `user: PUID:PGID` in docker-compose, these ARGs are not strictly necessary
# for the user/group creation, but they are still useful if you build with them.
ARG PUID=1000
ARG PGID=1000

# Install all build dependencies including Comskip requirements
RUN apt-get update -o Acquire::Check-Valid-Until=false \
    && apt-get install -y --no-install-recommends \
        ca-certificates git curl bash unzip ffmpeg \
        build-essential autoconf automake libtool \
        libargtable2-dev pkg-config libsdl2-dev \
        libavcodec-dev libavformat-dev libavfilter-dev libavutil-dev \
        libavdevice-dev libjansson-dev \
    && rm -rf /var/lib/apt/lists/*

# Create a dedicated user and group for the application
# IMPORTANT: We are no longer forcing specific GID/UIDs here, allowing the system
# to assign available IDs. Docker's 'user' directive in docker-compose will handle
# mapping the host's PUID/PGID to this user at runtime, regardless of its internal UID/GID.
RUN groupadd uhf-server \
    && useradd -g uhf-server -s /bin/bash -m uhf-server

# Build and install Comskip from source
# Comskip is installed globally, so its permissions are less critical for the specific user.
RUN cd /tmp \
    && git clone --depth 1 https://github.com/erikkaashoek/Comskip.git \
    && cd Comskip \
    && ./autogen.sh \
    && ./configure \
    && make \
    && make install \
    && cd / \
    && rm -rf /tmp/Comskip

# Install UHF server with specific version
ARG TARGETARCH
ARG UHF_VERSION
# Define INSTALL_DIR as an ARG to make it configurable if needed, and accessible for chown
ARG INSTALL_DIR="/opt/uhf-server"
RUN REPO="swapplications/uhf-server-dist" \
    && BIN_NAME="uhf-server" \
    && ARCH="$TARGETARCH" \
    && if [ "$ARCH" = "amd64" ]; then \
          PLATFORM="x64"; \
        elif [ "$ARCH" = "arm64" ]; then \
          PLATFORM="arm64"; \
        else \
          echo "❌ Unsupported architecture: $ARCH" && exit 1; \
        fi \
    && echo "🔖 Installing version: $UHF_VERSION" \
    && ASSET_FILENAME="UHF.Server-linux-${PLATFORM}-${UHF_VERSION}.zip" \
    && ASSET_URL="https://github.com/$REPO/releases/download/${UHF_VERSION}/${ASSET_FILENAME}" \
    && echo "📥 Downloading from: $ASSET_URL" \
    && TMP_DIR=$(mktemp -d) \
    && curl -L "$ASSET_URL" -o "$TMP_DIR/uhf-server.zip" \
    && echo "📦 Unzipping..." \
    && unzip -q "$TMP_DIR/uhf-server.zip" -d "$TMP_DIR/extracted" \
    && echo "🚚 Installing to $INSTALL_DIR..." \
    && rm -rf "$INSTALL_DIR" \
    && mkdir -p "$INSTALL_DIR" \
    && cp -r "$TMP_DIR/extracted/"* "$INSTALL_DIR" \
    && ln -sf "$INSTALL_DIR/$BIN_NAME" /usr/local/bin/$BIN_NAME \
    && chmod +x "$INSTALL_DIR/$BIN_NAME" \
    && rm -rf "$TMP_DIR" \
    && echo "✅ UHF Server $UHF_VERSION installed successfully!"

# Create directory for recordings and database, and set ownership
# The /var/lib/uhf-server and its 'recordings' subdirectory must be writable
# by the 'uhf-server' user (or the user specified in docker-compose).
RUN mkdir -p /var/lib/uhf-server/recordings \
    && chown -R uhf-server:uhf-server /var/lib/uhf-server

# Switch to the non-root user
# This ensures that all subsequent commands (including CMD) run as 'uhf-server'
# if the 'user' directive is not explicitly set in docker-compose.
USER uhf-server

# Set working directory for the user
WORKDIR /var/lib/uhf-server

# Start bash as the default command (can be overridden by docker-compose)
CMD ["bash"]
```
