### ISSUE TITLE
Update docker-compose.yml to simplify port/volume mappings

### ISSUE THREAD

**Issue by taserface-x** [solid-pixel/uhf-server-docker#12]
``` 
#docker-compose.yml

services:
  uhf-server:
    image: uhf-server:latest 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uhf-server
    restart: unless-stopped
    environment:
      - PASSWORD=${PASSWORD:-} # Optional password protection
    volumes:
      - ./data:/var/lib/uhf-server #Persist UHF settings
      - /mnt/recordings:/recordings #Recordings go in /mnt/recordings - you can set this to whatever you want
    ports:
      - 8000:8000 # Change the first number if you want a different port
    stop_grace_period: 30s

```
