### ISSUE TITLE
Endlessly deploying, yet working fine

### ISSUE THREAD

**Issue by NewsGuyTor** [solid-pixel/uhf-server-docker#14]
Since updating my YAML to the latest image (any reason the Docker compose image ain't just "solidpixel/uhf-server:latest" btw?), thing still work and record fine, but the app is just endlessly "Deploying" on TrueNAS:

<img width="591" alt="Image" src="https://github.com/user-attachments/assets/62bb199d-e8d7-4a75-b128-87642f46686e" />

The Docker log just shows what seems to be normal startup stuff:
<img width="933" alt="Image" src="https://github.com/user-attachments/assets/e8ee3424-e2e7-4a74-b612-3170e0da8243" />

Here's my YAML in case that helps.

```
services:
  uhf-server:
    command:
      - uhf-server
    container_name: uhf-server
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=30000
      - RECORDINGS_DIR=/var/lib/uhf-server/recordings
      - DB_PATH=/var/lib/uhf-server/db.json
      - LOG_LEVEL=INFO
    image: solidpixel/uhf-server:1.2.0-ffmpeg7.0.2
    ports:
      - '30000:30000'
    restart: unless-stopped
    volumes:
      - /mnt/data/media/Recordings:/var/lib/uhf-server/recordings
      - /mnt/apps/jelly-arr-dlers-etc/uhf-server:/var/lib/uhf-server/
    working_dir: /uhf-data
version: '3.8'
```

**Comment by solid-pixel** [comment]
I think the issue is that the new image has a hardcoded healthcheck that pings the server internally on port 8000, but you changed it to 30000. That makes the healthcheck fail, even though the app itself still works fine.

There’s usually no need to change the internal port, it’s easier to leave it at 8000 and just remap the external one.

Try this docker-compose.yml and let me know if it fixes the problem. If it does, I’ll look into moving the healthcheck logic into docker-compose so folks can tweak the port if needed.

You’ll still be able to connect to port 30000 from outside, as this only changes the internal port inside the container.

```yaml
version: '3.8'

services:
  uhf-server:
    image: solidpixel/uhf-server:1.2.0-ffmpeg7.0.2
    container_name: uhf-server
    command:
      - uhf-server
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000  # internal port used by the app and healthcheck
      - RECORDINGS_DIR=/var/lib/uhf-server/recordings
      - DB_PATH=/var/lib/uhf-server/db.json
      - LOG_LEVEL=INFO
    ports:
      - '30000:8000'  # external:internal port mapping
    volumes:
      - /mnt/data/media/Recordings:/var/lib/uhf-server/recordings
      - /mnt/apps/jelly-arr-dlers-etc/uhf-server:/var/lib/uhf-server/
    restart: unless-stopped
```

> Why not just use solidpixel/uhf-server:latest?

I prefer pinning to a specific version so users can easily see which image they’re running. Makes it clearer when something’s changed or a new release is out.
