### ISSUE TITLE
FFMpeg Version

### ISSUE THREAD

**Issue by ianweatherburn** [solid-pixel/uhf-server-docker#9]
I noticed the the image `debian:bookworm-slim `contains version `ffmpeg version 5.1.6-0+deb12u1` which appears to be creating corrupted .mp4 files during recording.
Not playable in the UHF app or via the source system.

ffmpeg reports:
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5f4b5313e7c0] moov atom not found
[in#0 @ 0x5f4b5313e6c0] Error opening input: Invalid data found when processing input
Error opening input file 39a3c1a6-6ae6-444f-8abb-84cbff6f2db6.mp4.
Error opening input files: Invalid data found when processing input
```

Have you been able to successfully record with this container?
Is it possible to include ffmpeg version 7 in your container? Not even sure that helps though? 
Are you able to play your .mp4 recordings?

**Comment by solid-pixel** [comment]
I had that issue back when I was using ffmpeg 4 on Linux, but switching to v5 should default to .ts files instead of .mp4.

I have reports from multiple users who are able to record and play successfully, especially after the uhf dev released `uhf-server` 1.2 earlier today. 

What are you running docker on? What OS and what cpu architecture?

Depending on when you first installed this, you might wanna try delete everything and reinstall by following the instructions on the README as I've pushed some significant changes yesterday and today.

**Comment by ianweatherburn** [comment]
Strange, as its definitely recording .mp4 files.
I'm on Ubuntu 24.04.

I have deleted the container multiple times when trying things, and removed and re-added the server to UHF, but will try again.

My docker-compose is pretty much like yours, just different paths:

```
services:
  uhf-server:
    image: solidpixel/uhf-server:latest
    container_name: uhf-server
    restart: unless-stopped
    volumes:
      - /home/iwadmin/docker/appdata/uhf-server/data:/var/lib/uhf-server
      - /media/videos/uhf-server/recordings:/recordings
    working_dir: /home/iwadmin/docker/appdata/uhf-server/data
    network_mode: host
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=32800
      - RECORDINGS_DIR=/recordings
      - DB_PATH=/var/lib/uhf-server/db.json
      - LOG_LEVEL=INFO
    command: ["uhf-server"]
```
dockerfile as per yours
```
FROM debian:bookworm-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    bash \
    ffmpeg \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Define a fake sudo so the script doesn't break
RUN echo '#!/bin/bash\n"$@"' > /usr/local/bin/sudo && chmod +x /usr/local/bin/sudo

# Install UHF CLI
RUN curl -sL https://link.uhfapp.com/setup.sh | bash

WORKDIR /data

RUN mkdir -p /var/lib/uhf-server

CMD ["bash"]
```
